const { Worker } = require('bullmq');
const { Octokit } = require('@octokit/rest');
const dotenv = require('dotenv');
const mongoose = require('mongoose');
const User = require('../models/User');
const Review = require('../models/Review');

dotenv.config();

// Connect to Database
mongoose.connect(process.env.MONGODB_URI)
  .then(() => console.log('Worker connected to MongoDB'))
  .catch(err => console.error('Worker MongoDB connection error:', err));

const connection = {
  host: process.env.REDIS_HOST ? process.env.REDIS_HOST.trim() : '127.0.0.1',
  port: process.env.REDIS_PORT ? parseInt(process.env.REDIS_PORT) : 6379,
  password: process.env.REDIS_PASSWORD ? process.env.REDIS_PASSWORD.trim() : undefined,
  tls: process.env.REDIS_HOST && process.env.REDIS_HOST.includes('upstash') ? { rejectUnauthorized: false } : undefined,
  maxRetriesPerRequest: null
};

const worker = new Worker('pr-reviews', async (job) => {
  const { repoFullName, owner, repoName, pullRequestNumber, userId } = job.data;
  console.log(`[Worker] Starting review for ${repoFullName} PR #${pullRequestNumber}`);

  try {
    // 1. Get user to retrieve their access token
    const user = await User.findById(userId);
    if (!user || !user.accessToken) {
      throw new Error('User not found or missing GitHub Access Token');
    }

    const octokit = new Octokit({ auth: user.accessToken });

    // 2. Fetch PR Diffs
    const { data: diffData } = await octokit.pulls.get({
      owner,
      repo: repoName,
      pull_number: pullRequestNumber,
      mediaType: { format: 'diff' }
    });

    console.log(`[Worker] Fetched diff for PR #${pullRequestNumber}. Diff length: ${diffData.length}`);

    // 3. Send Diff to AI
    console.log(`[Worker] Sending to AI for analysis...`);
    const { analyzeCodeWithAI } = require('../utils/aiReviewer');
    const aiComments = await analyzeCodeWithAI(diffData);

    console.log(`[Worker] AI Analysis complete. Found ${aiComments.length} suggestions.`);

    // 4. Post comments back to GitHub
    if (aiComments && aiComments.length > 0) {
      const { data: pullRequest } = await octokit.pulls.get({
        owner,
        repo: repoName,
        pull_number: pullRequestNumber
      });
      const commit_id = pullRequest.head.sha;

      const comments = aiComments.map(comment => ({
        path: comment.path,
        position: comment.position,
        body: comment.body
      }));

      try {
        await octokit.pulls.createReview({
          owner,
          repo: repoName,
          pull_number: pullRequestNumber,
          commit_id,
          event: 'COMMENT',
          comments
        });
        console.log(`[Worker] Successfully posted review comments to PR #${pullRequestNumber}`);
      } catch (err) {
        console.warn(`[Worker] Failed to post inline comments, falling back to general PR comment. Reason: ${err.message}`);
        
        // Fallback to a single issue comment
        let fallbackBody = "**SyntaxShield AI Code Review**\n\n";
        aiComments.forEach(c => {
          fallbackBody += `**File:** \`${c.path}\` (Diff pos: ${c.position})\n> ${c.body}\n\n`;
        });
        
        await octokit.issues.createComment({
          owner,
          repo: repoName,
          issue_number: pullRequestNumber,
          body: fallbackBody
        });
      }
    } else {
       console.log(`[Worker] No comments generated by AI.`);
    }

    // 5. Save record of review to database
    const savedReview = await Review.create({
      userId,
      repoFullName,
      pullRequestNumber,
      commentCount: aiComments ? aiComments.length : 0,
      status: 'success',
      comments: aiComments ? aiComments.map(c => ({
        path: c.path,
        line: c.line || 0,
        body: c.body
      })) : []
    });

    return JSON.stringify({
      userId,
      repoFullName,
      pullRequestNumber,
      commentCount: savedReview.commentCount,
      status: 'success',
      reviewId: savedReview._id
    });
    
  } catch (err) {
    console.error(`[Worker Error] Failed to process job ${job.id}:`, err.message);
    
    // Log failure
    await Review.create({
      userId: job.data.userId,
      repoFullName: job.data.repoFullName,
      pullRequestNumber: job.data.pullRequestNumber,
      commentCount: 0,
      status: 'failed'
    });

    return JSON.stringify({
      userId: job.data.userId,
      status: 'failed'
    });

    throw err;
  }
}, { connection });

worker.on('completed', job => {
  console.log(`Job ${job.id} has completed!`);
});

worker.on('failed', (job, err) => {
  console.log(`Job ${job.id} has failed with ${err.message}`);
});

module.exports = worker;
